#!/bin/bash

# 📚 COMANDOS ÚTILES - Portfolio Angular

echo "🎯 COMANDOS DE DESARROLLO"
echo ""
echo "Iniciar servidor de desarrollo:"
echo "  npm start"
echo ""
echo "Hacer build de producción:"
echo "  npm run build"
echo ""
echo "Ver build en navegador:"
echo "  npm run build && npx http-server dist/manuelreeb/browser -p 8080"
echo ""

echo "🔧 DESARROLLO"
echo ""
echo "Generar nuevo componente:"
echo "  ng generate component components/nuevo-componente"
echo ""
echo "Generar nuevo servicio:"
echo "  ng generate service services/nuevo-servicio"
echo ""

echo "🌐 GIT"
echo ""
echo "Conectar a GitHub:"
echo "  git remote add origin https://github.com/tu-username/portfolio.git"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""
echo "Ver cambios pendientes:"
echo "  git status"
echo ""
echo "Ver historial:"
echo "  git log --oneline"
echo ""

echo "🐳 DOCKER"
echo ""
echo "Construir imagen:"
echo "  docker build -t manuelreeb-portfolio ."
echo ""
echo "Ejecutar contenedor:"
echo "  docker run -p 3000:3000 manuelreeb-portfolio"
echo ""

echo "📦 NPM"
echo ""
echo "Instalar dependencias:"
echo "  npm install"
echo ""
echo "Actualizar dependencias:"
echo "  npm update"
echo ""
echo "Ver dependencias desactualizadas:"
echo "  npm outdated"
echo ""

echo "📊 ANÁLISIS"
echo ""
echo "Ver tamaño del bundle:"
echo "  npm run build -- --stats-json"
echo "  npx webpack-bundle-analyzer dist/manuelreeb/browser/stats.json"
echo ""

echo "🧪 TESTING"
echo ""
echo "Ejecutar tests:"
echo "  npm test"
echo ""
echo "Tests en CI (single run):"
echo "  npm run test:ci"
echo ""

echo "✅ CHECKLIST ANTES DE PUBLICAR"
echo ""
echo "□ Actualizar información personal en about.ts"
echo "□ Agregar proyectos reales en projects.ts"
echo "□ Actualizar stack técnico en stack.ts"
echo "□ Cambiar logos de empresas en companies.ts"
echo "□ Actualizar links de redes sociales"
echo "□ Reemplazar avatar/fotos"
echo "□ Cambiar dominio en .github/workflows/ci-cd.yml"
echo "□ Conectar repositorio a GitHub"
echo "□ Habilitar GitHub Pages"
echo "□ Apuntar dominio"
echo ""

echo "🚀 DEPLOYMENT"
echo ""
echo "GitHub Pages:"
echo "  - Automático con cada push a main"
echo ""
echo "Vercel:"
echo "  - Conectar repo y dejar configuración por defecto"
echo ""
echo "Netlify:"
echo "  - Build: npm run build"
echo "  - Publish dir: dist/manuelreeb/browser"
echo ""
echo "Docker/VPS:"
echo "  docker build -t portfolio . && docker run -p 3000:3000 portfolio"
echo ""

echo "📝 PERSONALIZACIÓN"
echo ""
echo "Cambiar colores principales:"
echo "  Editar: tailwind.config.js (theme.extend.colors)"
echo ""
echo "Cambiar fuente:"
echo "  Editar: tailwind.config.js (theme.extend.fontFamily)"
echo ""
echo "Agregar nuevas secciones:"
echo "  ng generate component components/nueva-seccion"
echo "  Importar en app.ts"
echo "  Agregar en app.html"
echo ""
